apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-http
  namespace: laravel-app
  labels:
    app: laravel-http
    component: frontend
    mode: http
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel-http
      mode: http
  template:
    metadata:
      labels:
        app: laravel-http
        mode: http
        component: frontend
    spec:
      imagePullSecrets:
        - name: github-registry-secret
      containers:
        - name: laravel-http
          image: ghcr.io/zyoshu-inc/zyoshu-modular:latest
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          env:
            - name: CONTAINER_MODE
              value: "http"
          envFrom:
            - secretRef:
                name: laravel-secrets
            - configMapRef:
                name: laravel-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: laravel-storage
              mountPath: /app/storage
      volumes:
        - name: laravel-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: laravel-http-service
  namespace: laravel-app
  labels:
    app: laravel-http
    component: frontend
spec:
  selector:
    app: laravel-http
    mode: http
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: laravel-http-hpa
  namespace: laravel-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: laravel-http
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
